# Generated by Django 4.2.6 on 2023-11-01 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "subject_num",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("subject_name", models.CharField(max_length=70)),
                ("classification", models.CharField(max_length=45)),
                ("classification_ge", models.CharField(max_length=45)),
                ("professor", models.CharField(max_length=50)),
                ("subject_credit", models.IntegerField()),
                ("major_ge", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("classification", models.CharField(max_length=45)),
                ("classification_ge", models.CharField(max_length=45)),
                ("subject_num", models.CharField(max_length=10)),
                ("subject_name", models.CharField(max_length=70)),
                ("subject_credit", models.IntegerField()),
                ("delete", models.BooleanField(null=True)),
                ("msc", models.CharField(max_length=70, null=True)),
                ("msc_type", models.CharField(max_length=70, null=True)),
                ("eng_sub", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="비밀번호는 대문자, 소문자, 특수 문자 및 숫자를 포함해야 합니다.",
                                regex="^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]+$",
                            )
                        ],
                    ),
                ),
                ("year", models.IntegerField()),
                ("major", models.CharField(max_length=45)),
                ("sub_major", models.CharField(blank=True, max_length=45, null=True)),
                ("name", models.CharField(max_length=45)),
                ("thesis", models.BooleanField()),
                ("eng", models.IntegerField(blank=True, null=True)),
                ("eg", models.BooleanField()),
                ("sum_credit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_year", models.IntegerField()),
                ("u_semester", models.IntegerField()),
                ("star", models.IntegerField()),
                ("content", models.TextField()),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.userinfo",
                    ),
                ),
                (
                    "subject_num",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.lecture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.userinfo",
                    ),
                ),
                (
                    "subject_num",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.lecture",
                    ),
                ),
            ],
        ),
    ]
