# Generated by Django 4.2.6 on 2023-11-01 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_userlecture_alter_lecture_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userlecture",
            options={},
        ),
        migrations.AlterModelTable(
            name="relation",
            table="relation",
        ),
        migrations.AlterModelTable(
            name="review",
            table="review",
        ),
        migrations.AlterModelTable(
            name="standard",
            table="standard",
        ),
        migrations.AlterModelTable(
            name="userinfo",
            table="user_info",
        ),
    ]
